export const SCHEMA_VERSION = 1;
const clone = (value) => structuredClone(value);
const now = () => new Date().toISOString();
function id(prefix) { const uuid = globalThis.crypto?.randomUUID?.(); if (!uuid) throw new Error('crypto.randomUUID is required'); return `${prefix}_${uuid}`; }
function asBytes(value) { if (value instanceof Uint8Array) return value; if (value instanceof ArrayBuffer) return new Uint8Array(value); if (ArrayBuffer.isView(value)) return new Uint8Array(value.buffer, value.byteOffset, value.byteLength); throw new Error('bytes must be an ArrayBuffer or typed array'); }
export async function hashBytes(bytes) { if (!globalThis.crypto?.subtle) throw new Error('Web Crypto subtle API is required'); const view = asBytes(bytes); const digest = await globalThis.crypto.subtle.digest('SHA-256', view); return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join(''); }
function assertAssetStore(assetStore) { if (!assetStore || typeof assetStore.put !== 'function' || typeof assetStore.get !== 'function') throw new Error('assetStore must implement put(checksum, bytes) and get(checksum)'); }
const STROKE_PRESETS = new Set(['round']); const HEX_COLOR = /^#[0-9a-fA-F]{6}$/;
function unitInterval(value, label) { if (!Number.isFinite(value) || value < 0 || value > 1) throw new Error(`${label} must be between 0 and 1`); return value; }
function normalizeStrokePoints(points) { if (!Array.isArray(points) || points.length < 2) throw new Error('stroke requires at least two points'); return points.map((point) => { if (!point || !Number.isFinite(point.x) || !Number.isFinite(point.y)) throw new Error('stroke points require finite x/y'); return { x: point.x, y: point.y, pressure: unitInterval(point.pressure ?? 1, 'stroke pressure') }; }); }
function normalizeStrokeStyle(style = {}) { const width = style.width ?? 2; const opacity = style.opacity ?? 1; const preset = style.preset ?? 'round'; const color = style.color ?? '#000000'; if (!Number.isFinite(width) || width <= 0) throw new Error('stroke width must be positive'); if (!STROKE_PRESETS.has(preset)) throw new Error('unsupported stroke preset'); if (typeof color !== 'string' || !HEX_COLOR.test(color)) throw new Error('stroke color must be #RRGGBB'); return { preset, color: color.toLowerCase(), width, opacity: unitInterval(opacity, 'stroke opacity') }; }
function normalizeTransformPatch(transform) { if (!transform || typeof transform !== 'object' || Array.isArray(transform)) throw new Error('transform must be an object'); const allowed = new Set(['x', 'y', 'scaleX', 'scaleY', 'rotationDeg']); const patch = {}; for (const [key, value] of Object.entries(transform)) { if (!allowed.has(key)) throw new Error(`unsupported transform field: ${key}`); if (!Number.isFinite(value)) throw new Error(`${key} must be finite`); if ((key === 'scaleX' || key === 'scaleY') && value === 0) throw new Error(`${key} must be non-zero`); patch[key] = value; } return patch; }
export function createProject({ ownerId, name = 'Untitled project' }) { if (!ownerId) throw new Error('ownerId is required'); const timestamp = now(); return { schemaVersion: SCHEMA_VERSION, projectId: id('project'), ownerId, name, revision: 0, createdAt: timestamp, updatedAt: timestamp, artboards: [], assets: {}, objects: {}, bodyTargets: {}, placements: {}, reviews: {}, exports: {}, history: [] }; }
export async function importAsset(project, { bytes, mimeType, width, height, provenance, licenseRef = null }, assetStore) { assertAssetStore(assetStore); const sourceBytes = asBytes(bytes); const checksum = await hashBytes(sourceBytes); const existing = Object.values(project.assets).find((asset) => asset.checksum === checksum); await assetStore.put(checksum, sourceBytes); if (existing) return { project, assetId: existing.assetId, deduplicated: true }; const assetId = id('asset'); const next = clone(project); next.assets[assetId] = { assetId, checksum, byteLength: sourceBytes.byteLength, mimeType, width, height, provenance, licenseRef, immutable: true }; return { project: commit(next, project, 'asset.import', { assetId, checksum }), assetId, deduplicated: false }; }
export async function verifyAssetSource(project, assetId, assetStore) { assertAssetStore(assetStore); const asset = project.assets[assetId]; if (!asset) throw new Error('asset not found'); const bytes = await assetStore.get(asset.checksum); if (bytes == null) throw new Error(`source bytes missing for asset: ${assetId}`); const sourceBytes = asBytes(bytes); if (sourceBytes.byteLength !== asset.byteLength) throw new Error(`source bytes corrupt for asset: ${assetId}`); const checksum = await hashBytes(sourceBytes); if (checksum !== asset.checksum) throw new Error(`source checksum mismatch for asset: ${assetId}`); return sourceBytes; }
export function applyCommand(project, command) { const next = clone(project); switch (command.type) {
case 'artboard.add': { const artboardId = command.artboardId ?? id('artboard'); next.artboards.push({ artboardId, widthMm: command.widthMm, heightMm: command.heightMm, units: 'mm', objectIds: [] }); return commit(next, project, command.type, { artboardId }); }
case 'object.add': { if (!next.assets[command.assetId]) throw new Error('asset not found'); const artboard = next.artboards.find((item) => item.artboardId === command.artboardId); if (!artboard) throw new Error('artboard not found'); const objectId = command.objectId ?? id('object'); if (next.objects[objectId]) throw new Error('object already exists'); next.objects[objectId] = { objectId, type: command.objectType ?? 'image', sourceAssetId: command.assetId, transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotationDeg: 0 }, masks: [], visible: true, locked: false }; artboard.objectIds.push(objectId); return commit(next, project, command.type, { objectId, artboardId: artboard.artboardId }); }
case 'stroke.add': { const artboard = next.artboards.find((item) => item.artboardId === command.artboardId); if (!artboard) throw new Error('artboard not found'); const objectId = command.objectId ?? id('stroke'); if (next.objects[objectId]) throw new Error('object already exists'); next.objects[objectId] = { objectId, type: 'stroke', sourceAssetId: null, coordinateSpace: 'artboard-mm', points: normalizeStrokePoints(command.points), style: normalizeStrokeStyle(command.style), transform: { x: 0, y: 0, scaleX: 1, scaleY: 1, rotationDeg: 0 }, masks: [], visible: true, locked: false }; artboard.objectIds.push(objectId); return commit(next, project, command.type, { objectId, artboardId: artboard.artboardId }); }
case 'object.remove': { const object = next.objects[command.objectId]; if (!object) throw new Error('object not found'); const artboard = next.artboards.find((item) => item.objectIds.includes(command.objectId)); if (!artboard) throw new Error('object artboard not found'); if (Object.values(next.placements).some((placement) => placement.objectId === command.objectId)) throw new Error('cannot remove placed object'); artboard.objectIds = artboard.objectIds.filter((objectId) => objectId !== command.objectId); delete next.objects[command.objectId]; return commit(next, project, command.type, { objectId: command.objectId, artboardId: artboard.artboardId }); }
case 'object.transform': { const object = next.objects[command.objectId]; if (!object) throw new Error('object not found'); object.transform = { ...object.transform, ...normalizeTransformPatch(command.transform) }; return commit(next, project, command.type, { objectId: command.objectId }); }
case 'body.add': { const bodyTargetId = command.bodyTargetId ?? id('body'); next.bodyTargets[bodyTargetId] = { bodyTargetId, kind: command.kind, sourceAssetId: command.sourceAssetId ?? null, coordinateFrame: command.coordinateFrame, calibration: command.calibration ?? null, uncertainty: command.uncertainty ?? 'unmeasured' }; return commit(next, project, command.type, { bodyTargetId }); }
case 'placement.set': { if (!next.objects[command.objectId]) throw new Error('object not found'); if (!next.bodyTargets[command.bodyTargetId]) throw new Error('body target not found'); const placementId = command.placementId ?? id('placement'); next.placements[placementId] = { placementId, objectId: command.objectId, designRevision: project.revision, bodyTargetId: command.bodyTargetId, frame: command.frame, physicalSizeMm: command.physicalSizeMm ?? null, deformation: command.deformation ?? null }; return commit(next, project, command.type, { placementId }); }
case 'review.approve': { const reviewId = command.reviewId ?? id('review'); const approvedRevision = project.revision + 1; next.reviews[reviewId] = { reviewId, revision: approvedRevision, authorId: command.authorId, status: 'approved', createdAt: now() }; return commit(next, project, command.type, { reviewId, approvedRevision }); }
default: throw new Error(`unsupported command: ${command.type}`); } }
export function isApprovalCurrent(project, reviewId) { const review = project.reviews[reviewId]; return Boolean(review && review.status === 'approved' && review.revision === project.revision); }
export function serializeProject(project) { return JSON.stringify(project); }
export function reopenProject(serialized) { const project = JSON.parse(serialized); if (project.schemaVersion !== SCHEMA_VERSION) throw new Error(`unsupported schemaVersion: ${project.schemaVersion}`); return project; }
function commit(next, previous, type, detail) { next.revision = previous.revision + 1; next.updatedAt = now(); next.history.push({ revision: next.revision, type, detail, committedAt: next.updatedAt }); return next; }